create table if not exists public.obra_tarefas (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.dashboard_obras(id) on delete cascade,
  ordem integer not null default 0,
  titulo text not null,
  responsavel text,
  horario text,
  status text not null default 'planejado',
  created_at timestamptz not null default now()
);

create table if not exists public.obra_pendencias (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.dashboard_obras(id) on delete cascade,
  ordem integer not null default 0,
  titulo text not null,
  impacto text,
  dono text,
  tipo text default 'geral',
  status text not null default 'aguardando',
  created_at timestamptz not null default now()
);

create table if not exists public.obra_checklists (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.dashboard_obras(id) on delete cascade,
  ordem integer not null default 0,
  item text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.obra_apontamentos (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.dashboard_obras(id) on delete cascade,
  ordem integer not null default 0,
  autor text not null,
  texto text not null,
  data_label text,
  created_at timestamptz not null default now()
);

create table if not exists public.obra_fotos (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.dashboard_obras(id) on delete cascade,
  ordem integer not null default 0,
  titulo text not null,
  tag text not null,
  finalidade text default 'Avanço',
  data_label text,
  image_url text,
  created_at timestamptz not null default now()
);

create index if not exists obra_tarefas_obra_id_idx
  on public.obra_tarefas (obra_id, ordem);

create index if not exists obra_pendencias_obra_id_idx
  on public.obra_pendencias (obra_id, ordem);

create index if not exists obra_checklists_obra_id_idx
  on public.obra_checklists (obra_id, ordem);

create index if not exists obra_apontamentos_obra_id_idx
  on public.obra_apontamentos (obra_id, ordem);

create index if not exists obra_fotos_obra_id_idx
  on public.obra_fotos (obra_id, ordem);
