create table if not exists public.dashboard_obras (
  id bigint primary key,
  nome text not null,
  slug text,
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.dashboard_obras enable row level security;

create table if not exists public.obra_tarefas (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.dashboard_obras(id) on delete cascade,
  ordem integer not null default 0,
  titulo text not null,
  responsavel text,
  horario text,
  status text not null default 'planejado',
  created_at timestamptz not null default now()
);

create table if not exists public.obra_pendencias (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.dashboard_obras(id) on delete cascade,
  ordem integer not null default 0,
  titulo text not null,
  impacto text,
  dono text,
  tipo text default 'geral',
  status text not null default 'aguardando',
  created_at timestamptz not null default now()
);

create table if not exists public.obra_checklists (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.dashboard_obras(id) on delete cascade,
  ordem integer not null default 0,
  item text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.obra_apontamentos (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.dashboard_obras(id) on delete cascade,
  ordem integer not null default 0,
  autor text not null,
  texto text not null,
  data_label text,
  created_at timestamptz not null default now()
);

create table if not exists public.obra_fotos (
  id bigint generated by default as identity primary key,
  obra_id bigint not null references public.dashboard_obras(id) on delete cascade,
  ordem integer not null default 0,
  titulo text not null,
  tag text not null,
  finalidade text default 'Avanço',
  data_label text,
  image_url text,
  created_at timestamptz not null default now()
);

create index if not exists dashboard_obras_updated_at_idx
  on public.dashboard_obras (updated_at desc);

create index if not exists obra_tarefas_obra_id_idx
  on public.obra_tarefas (obra_id, ordem);

create index if not exists obra_pendencias_obra_id_idx
  on public.obra_pendencias (obra_id, ordem);

create index if not exists obra_checklists_obra_id_idx
  on public.obra_checklists (obra_id, ordem);

create index if not exists obra_apontamentos_obra_id_idx
  on public.obra_apontamentos (obra_id, ordem);

create index if not exists obra_fotos_obra_id_idx
  on public.obra_fotos (obra_id, ordem);

create policy "authenticated read dashboard obras"
on public.dashboard_obras
for select
to authenticated
using (true);

create policy "authenticated write dashboard obras"
on public.dashboard_obras
for all
to authenticated
using (true)
with check (true);

insert into storage.buckets (id, name, public)
values ('obra-midias', 'obra-midias', false)
on conflict (id) do nothing;

create policy "authenticated read obra midias"
on storage.objects
for select
to authenticated
using (bucket_id = 'obra-midias');

create policy "authenticated upload obra midias"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'obra-midias');

create policy "authenticated update obra midias"
on storage.objects
for update
to authenticated
using (bucket_id = 'obra-midias')
with check (bucket_id = 'obra-midias');

create policy "authenticated delete obra midias"
on storage.objects
for delete
to authenticated
using (bucket_id = 'obra-midias');
